"""
Revision ID: 8e46b434b89b
Revises: e9286bf87736
Create Date: 2025-09-22 15:56:35.543327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e46b434b89b'
down_revision = 'e9286bf87736'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('Id_Categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_Categoria', sa.String(length=100), nullable=True),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Categoria')
    )
    op.create_table('fuentes',
    sa.Column('Id_Fuente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_Fuente', sa.String(length=100), nullable=True),
    sa.Column('Url_Fuente', sa.String(length=500), nullable=True),
    sa.Column('Tipo_Fuente', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id_Fuente')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('tipos_contenido',
    sa.Column('Id_Tipo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_Tipo', sa.String(length=50), nullable=True),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id_Tipo')
    )
    op.create_table('adjunto',
    sa.Column('id_adjunto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado', name='estado_adjunto'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_adjunto')
    )
    op.create_table('chat',
    sa.Column('id_chat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.Enum('privado', 'grupo', name='tipo_chat'), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_chat'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_table('etiqueta',
    sa.Column('id_etiqueta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=450), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'inactiva', name='estado_etiqueta'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_etiqueta')
    )
    op.create_table('foro',
    sa.Column('id_foro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=450), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estadoforo'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_foro')
    )
    op.create_table('grafica',
    sa.Column('id_grafica', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_grafica', sa.String(length=50), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'inactiva', name='estado_grafica'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_grafica')
    )
    op.create_table('usuario_rol',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_rol')
    )
    op.create_table('usuario_seguido',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_user_seguido', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_user_seguido'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_user_seguido')
    )
    op.create_table('usuario_seguidor',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_user_seguidor', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_user_seguidor'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_user_seguidor')
    )
    op.create_table('chat_mensaje',
    sa.Column('id_mensaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('enviado', 'leido', 'eliminado', name='estado_mensaje'), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id_chat'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('chat_miembro',
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('rol_chat', sa.Enum('admin', 'miembro', name='rol_chat'), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id_chat'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_chat', 'id_user')
    )
    op.create_table('comentarios_noticias',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Id_Noticia', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('fecha_comentario', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Id_Noticia'], ['noticias.Id_Noticia'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('dato_grafica',
    sa.Column('id_dato', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_grafica', sa.Integer(), nullable=True),
    sa.Column('etiqueta', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_grafica'], ['grafica.id_grafica'], ),
    sa.PrimaryKeyConstraint('id_dato')
    )
    op.create_table('publicacion',
    sa.Column('id_publicacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('foro_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('publicada', 'eliminada', 'archivada', name='estado_publicacion'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('cantidad_comentarios', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('fecha_ultima_actividad', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['foro_id'], ['foro.id_foro'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    op.create_table('chat_mensaje_adjunto',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_mensaje'], ['chat_mensaje.id_mensaje'], ),
    sa.PrimaryKeyConstraint('id_mensaje', 'id_adjunto')
    )
    op.create_table('comentario',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado', name='estado_comentario'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('comentarios_publicaciones',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Id_Publicacion', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('fecha_comentario', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Id_Publicacion'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('publicacion_adjunto',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_adjunto')
    )
    op.create_table('publicacion_etiqueta',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiqueta.id_etiqueta'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_etiqueta')
    )
    op.create_table('comentario_adjunto',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentario.id_comentario'], ),
    sa.PrimaryKeyConstraint('id_comentario', 'id_adjunto')
    )
    op.create_foreign_key(None, 'noticias', 'categorias', ['Id_Categoria'], ['Id_Categoria'])
    op.create_foreign_key(None, 'noticias', 'fuentes', ['Id_Fuente'], ['Id_Fuente'])
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_table('comentario_adjunto')
    op.drop_table('publicacion_etiqueta')
    op.drop_table('publicacion_adjunto')
    op.drop_table('comentarios_publicaciones')
    op.drop_table('comentario')
    op.drop_table('chat_mensaje_adjunto')
    op.drop_table('publicacion')
    op.drop_table('dato_grafica')
    op.drop_table('comentarios_noticias')
    op.drop_table('chat_miembro')
    op.drop_table('chat_mensaje')
    op.drop_table('usuario_seguidor')
    op.drop_table('usuario_seguido')
    op.drop_table('usuario_rol')
    op.drop_table('grafica')
    op.drop_table('foro')
    op.drop_table('etiqueta')
    op.drop_table('chat')
    op.drop_table('adjunto')
    op.drop_table('tipos_contenido')
    op.drop_table('rol')
    op.drop_table('fuentes')
    op.drop_table('categorias')
    # ### end Alembic commands ###