"""
Revision ID: e9286bf87736
Revises: 
Create Date: 2025-09-22 14:00:02.458653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9286bf87736'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id_user', sa.Integer(), primary_key=True, autoincrement=True, nullable=False, index=True),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('lastname', sa.String(length=50), nullable=False),
        sa.Column('cellphone', sa.String(length=20), nullable=False),
        sa.Column('direction', sa.String(length=120), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False, index=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('country', sa.String(length=50), nullable=False),
        sa.Column('rol', sa.Enum('administrador', 'usuario', name='roleenum'), nullable=False, server_default='usuario'),
        sa.Column('state', sa.Enum('activo', 'inactivo', name='stateuser'), nullable=False, server_default='activo'),
        sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_activity_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('number_followers', sa.Integer(), server_default='0'),
        sa.UniqueConstraint('username', name='uq_users_username'),
        sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('auditoria_usuario_estado',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id_usuario', sa.Integer(), nullable=False),
        sa.Column('estado_anterior', sa.Enum('activo', 'inactivo', name='estado_anterior'), nullable=True),
        sa.Column('estado_nuevo', sa.Enum('activo', 'inactivo', name='estado_nuevo'), nullable=True),
        sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['id_usuario'], ['users.id_user'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
        sa.Column('Id_Noticia', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('titulo', sa.String(length=200)),
        sa.Column('resumen', sa.Text()),
        sa.Column('enlace', sa.String(length=500)),
        sa.Column('fecha_publicacion', sa.TIMESTAMP(), server_default=sa.text('now()')),
        sa.Column('Id_Categoria', sa.Integer()),
        sa.Column('Id_Fuente', sa.Integer()),
        sa.Column('cantidad_comentarios', sa.Integer(), server_default='0'),
        sa.Column('likes', sa.Integer(), server_default='0'),
        sa.Column('dislikes', sa.Integer(), server_default='0')
    )
    op.create_table('reacciones',
        sa.Column('id_reaccion', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id_user', sa.Integer(), nullable=False),
        sa.Column('Id_Noticia', sa.Integer(), nullable=False),
        sa.Column('tipo_reaccion', sa.String(length=20), nullable=True),
        sa.Column('fecha_reaccion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['Id_Noticia'], ['noticias.Id_Noticia']),
        sa.ForeignKeyConstraint(['id_user'], ['users.id_user']),
        sa.PrimaryKeyConstraint('id_reaccion')
    )
    # Las alteraciones y drops de constraints se deben mover a una migración posterior
    # Las alteraciones y drops de constraints se deben mover a una migración posterior
    # Las alteraciones y drops de constraints se deben mover a una migración posterior
    # Las alteraciones y drops de constraints se deben mover a una migración posterior
	# Solo creación de tablas, sin alteraciones ni drops
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_seguidor', sa.Column('id_usuario_seguidor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('usuario_seguidor', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario_seguidor', type_='foreignkey')
    op.drop_constraint(None, 'usuario_seguidor', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_seguidor_ibfk_1'), 'usuario_seguidor', 'usuario', ['id_usuario'], ['id_usuario'])
    op.create_foreign_key(op.f('usuario_seguidor_ibfk_2'), 'usuario_seguidor', 'usuario', ['id_usuario_seguidor'], ['id_usuario'])
    op.drop_column('usuario_seguidor', 'id_user_seguidor')
    op.drop_column('usuario_seguidor', 'id_user')
    op.add_column('usuario_seguido', sa.Column('id_usuario_seguido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('usuario_seguido', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario_seguido', type_='foreignkey')
    op.drop_constraint(None, 'usuario_seguido', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_seguido_ibfk_2'), 'usuario_seguido', 'usuario', ['id_usuario_seguido'], ['id_usuario'])
    op.create_foreign_key(op.f('usuario_seguido_ibfk_1'), 'usuario_seguido', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_column('usuario_seguido', 'id_user_seguido')
    op.drop_column('usuario_seguido', 'id_user')
    op.add_column('usuario_rol', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuario_rol', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_rol_ibfk_1'), 'usuario_rol', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_column('usuario_rol', 'id_user')
    op.alter_column('rol', 'nombre_rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('publicacion', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'publicacion', type_='foreignkey')
    op.create_foreign_key(op.f('publicacion_ibfk_1'), 'publicacion', 'usuario', ['usuario_id'], ['id_usuario'])
    op.drop_column('publicacion', 'fecha_ultima_actividad')
    op.drop_column('publicacion', 'slug')
    op.drop_column('publicacion', 'cantidad_comentarios')
    op.drop_column('publicacion', 'id_user')
    op.drop_column('noticias', 'dislikes')
    op.drop_column('noticias', 'likes')
    op.drop_column('noticias', 'cantidad_comentarios')
    op.drop_constraint(None, 'grafica', type_='foreignkey')
    op.create_foreign_key(op.f('grafica_ibfk_1'), 'grafica', 'usuario', ['autor_id'], ['id_usuario'])
    op.drop_constraint(None, 'foro', type_='foreignkey')
    op.create_foreign_key(op.f('foro_ibfk_1'), 'foro', 'usuario', ['autor_id'], ['id_usuario'])
    op.alter_column('foro', 'autor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('foro', 'nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'etiqueta', type_='foreignkey')
    op.create_foreign_key(op.f('etiqueta_ibfk_1'), 'etiqueta', 'usuario', ['autor_id'], ['id_usuario'])
    op.add_column('comentario', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comentario', type_='foreignkey')
    op.create_foreign_key(op.f('comentario_ibfk_2'), 'comentario', 'usuario', ['usuario_id'], ['id_usuario'])
    op.drop_column('comentario', 'id_user')
    op.add_column('chat_miembro', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_miembro', type_='foreignkey')
    op.create_foreign_key(op.f('chat_miembro_ibfk_2'), 'chat_miembro', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_column('chat_miembro', 'id_user')
    op.add_column('chat_mensaje', sa.Column('hora_envio', mysql.TIME(), server_default=sa.text('curtime()'), nullable=True))
    op.add_column('chat_mensaje', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_mensaje', type_='foreignkey')
    op.create_foreign_key(op.f('chat_mensaje_ibfk_2'), 'chat_mensaje', 'usuario', ['id_usuario'], ['id_usuario'])
    op.alter_column('chat_mensaje', 'fecha_envio',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('curdate()'))
    op.drop_column('chat_mensaje', 'id_user')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key(op.f('chat_ibfk_1'), 'chat', 'usuario', ['creador_id'], ['id_usuario'])
    op.drop_constraint(None, 'adjunto', type_='foreignkey')
    op.create_foreign_key(op.f('adjunto_ibfk_1'), 'adjunto', 'usuario', ['autor_id'], ['id_usuario'])
    op.create_table('usuario',
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contrasena', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('estado', mysql.ENUM('activo', 'inactivo'), server_default=sa.text("'activo'"), nullable=True),
    sa.Column('verificacion', mysql.ENUM('pendiente', 'aprobado', 'rechazado'), server_default=sa.text("'pendiente'"), nullable=True),
    sa.Column('telefono', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pais', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('reacciones')
    op.drop_table('auditoria_usuario_estado')
    # ### end Alembic commands ###