"""
Revision ID: 0ce1cfe49526
Revises: 14c6f80d7c48
Create Date: 2025-11-09 17:44:46.103921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ce1cfe49526'
down_revision = '14c6f80d7c48'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('foro_ibfk_2'), 'foro', type_='foreignkey')
    op.create_foreign_key(None, 'foro', 'grafica', ['id_grafica'], ['id_grafica'])
    op.drop_column('foro', 'grafica_id')
    op.alter_column('grafica', 'titulo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('noticias', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('noticias', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('grafica', 'titulo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.add_column('foro', sa.Column('grafica_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'foro', type_='foreignkey')
    op.create_foreign_key(op.f('foro_ibfk_2'), 'foro', 'grafica', ['grafica_id'], ['id_grafica'])
    # ### end Alembic commands ###