"""
Revision ID: 0ede3c179cf8
Revises: 9461cff7e7f7
Create Date: 2025-10-01 13:36:52.570833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ede3c179cf8'
down_revision = '9461cff7e7f7'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noticias', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('users', 'cellphone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'direction',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'direction',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'cellphone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('noticias', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###