"""
Revision ID: 14c6f80d7c48
Revises: b3d9c1f3b1ab
Create Date: 2025-11-09 17:37:23.898387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14c6f80d7c48'
down_revision = 'b3d9c1f3b1ab'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('visibilidad', sa.Enum('publico', 'privado', name='visibilidad_chat'), nullable=True))
    op.add_column('dato_grafica', sa.Column('anio', sa.Integer(), nullable=True))
    op.add_column('dato_grafica', sa.Column('cop_usd', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('dato_grafica', sa.Column('cop_eur', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('dato_grafica', sa.Column('fecha_actualizacion', sa.Date(), nullable=True))
    op.add_column('foro', sa.Column('id_grafica', sa.Integer(), nullable=True))
    op.drop_index(op.f('grafica_id'), table_name='foro')
    op.drop_constraint(op.f('foro_ibfk_2'), 'foro', type_='foreignkey')
    op.create_foreign_key(None, 'foro', 'grafica', ['id_grafica'], ['id_grafica'])
    op.drop_column('foro', 'grafica_id')
    op.alter_column('grafica', 'titulo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('noticias', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('noticias', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('grafica', 'titulo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.add_column('foro', sa.Column('grafica_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'foro', type_='foreignkey')
    op.create_foreign_key(op.f('foro_ibfk_2'), 'foro', 'grafica', ['grafica_id'], ['id_grafica'])
    op.create_index(op.f('grafica_id'), 'foro', ['grafica_id'], unique=True)
    op.drop_column('foro', 'id_grafica')
    op.drop_column('dato_grafica', 'fecha_actualizacion')
    op.drop_column('dato_grafica', 'cop_eur')
    op.drop_column('dato_grafica', 'cop_usd')
    op.drop_column('dato_grafica', 'anio')
    op.drop_column('chat', 'visibilidad')
    # ### end Alembic commands ###