"""
Revision ID: 95eb5ff57d8f
Revises: ca7e65cf99df
Create Date: 2025-11-08 09:23:02.675808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95eb5ff57d8f'
down_revision = 'ca7e65cf99df'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('noticias', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('noticias', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###