"""
Revision ID: c7f7dc610fff
Revises: 0ce1cfe49526
Create Date: 2025-11-10 00:02:52.321372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7f7dc610fff'
down_revision = '0ce1cfe49526'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comentario_ibfk_3'), 'comentario', type_='foreignkey')
    op.drop_column('comentario', 'publicacion_id')
    op.alter_column('noticias', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('noticias', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.add_column('comentario', sa.Column('publicacion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('comentario_ibfk_3'), 'comentario', 'publicacion', ['publicacion_id'], ['id_publicacion'])
    # ### end Alembic commands ###