"""
Revision ID: d616928aa4b2
Revises: f0a0b167ca74
Create Date: 2025-09-29 22:43:05.853163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd616928aa4b2'
down_revision = 'f0a0b167ca74'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###