"""
Revision ID: f0a0b167ca74
Revises: add_profile_image_to_user
Create Date: 2025-09-29 21:21:34.048103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0a0b167ca74'
down_revision = 'add_profile_image_to_user'
branch_labels = None
depends_on = None

def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_seguido',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_user_seguido', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['id_user_seguido'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_user_seguido')
    )
    op.create_table('comentario',
    sa.Column('id_comentario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('foro_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado', name='estado_comentario'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['foro_id'], ['foro.id_foro'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('publicacion_etiqueta',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiqueta.id_etiqueta'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_etiqueta')
    )
    op.create_table('comentario_adjunto',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentario.id_comentario'], ),
    sa.PrimaryKeyConstraint('id_comentario', 'id_adjunto')
    )
    op.add_column('foro', sa.Column('grafica_id', sa.Integer(), nullable=False))
    op.alter_column('foro', 'estado',
               existing_type=mysql.ENUM('activo', 'inactivo'),
               nullable=False)
    op.create_unique_constraint(None, 'foro', ['grafica_id'])
    op.create_foreign_key(None, 'foro', 'grafica', ['grafica_id'], ['id_grafica'])
    op.alter_column('noticias', 'activa',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('noticias', 'cantidad_comentarios')
    op.drop_column('noticias', 'dislikes')
    op.drop_column('noticias', 'likes')
    op.alter_column('users', 'profile_image',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(length=1000000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.add_column('noticias', sa.Column('likes', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('noticias', sa.Column('dislikes', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('noticias', sa.Column('cantidad_comentarios', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('noticias', 'activa',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'foro', type_='foreignkey')
    op.drop_constraint(None, 'foro', type_='unique')
    op.alter_column('foro', 'estado',
               existing_type=mysql.ENUM('activo', 'inactivo'),
               nullable=True)
    op.drop_column('foro', 'grafica_id')
    op.drop_table('comentario_adjunto')
    op.drop_table('publicacion_etiqueta')
    op.drop_table('comentario')
    op.drop_table('usuario_seguido')
    # ### end Alembic commands ###