# Configuración de ejecución Locust
# Instrucciones:
# 1. pip install locust
# 2. locust -f tests_locust  (usando todos los archivos)
# 3. UI: http://localhost:8089
# 4. Para modo sólo CLI (headless=true) añadir --headless en comando.

headless = false
loglevel = INFO
host = http://127.0.0.1:8000
users = 10
spawn-rate = 2
run-time = 5m
